name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with autopep8
        run: |
          autopep8 --diff --recursive --exclude=dividends_env --exit-code .
      - name: Lint with pylint
        run: |
          pylint --rcfile=setup.cfg dividend_chaser runner.py
      - name: Database Schema
        run: |
          orator migrate -c dividend_chaser/config/database_test.py -f
      - name: Test with pytest
        env:
          TZ: America/Los_Angeles
        run: |
          pip install pytest
          ENVIRONMENT=test pytest
