name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with autopep8
      run: |
        pip3 install virtualenv
        virtualenv dividends_env
        source dividends_env/bin/activate
        pip3 install -r requirements.txt
        autopep8 --diff --recursive --exclude=dividends_env --exit-code .
    - name: Lint with pylint
      run: |
        pylint --rcfile=setup.cfg dividend_chaser
    - name: Test with pytest
      run: |
        pip install pytest
        py.test 

